services:
  db_honey:
    build: ./db 
    container_name: postgres_db_honey
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - honey_bot_postgres_data:/var/lib/postgresql/data
    networks:
      - tg_app_net_honey
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

  bot_honey:
    build: ./bot
    user: "1000:1000"
    container_name: tg_bot_honey
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./bot:/bot
      - bot_logs_honey:/app/logs
      - bot_media_honey:/app/media
    depends_on:
      db_honey:
        condition: service_healthy
    networks:
      - tg_app_net_honey

  log-viewer_honey:
    build: ./log_viewer
    user: "1000:1000"
    container_name: log_viewer_honey
    restart: unless-stopped
    env_file: .env
    ports:
      - "${LOG_VIEWER_PORT}:${LOG_VIEWER_PORT}"
    environment:
      # Явно передаем порт внутрь, чтобы python-скрипт его видел
      - LOG_VIEWER_PORT=${LOG_VIEWER_PORT}
    volumes:
      - bot_logs_honey:/app/logs:ro
    depends_on:
      - bot_honey
    networks:
      - tg_app_net_honey

volumes:
  honey_bot_postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/easysochi/postgres_honey
  media_honey:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/easysochi/media_honey
  bot_logs_honey:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/easysochi/logs_honey

networks:
  tg_app_net_honey:
    driver: bridge