"""initial autogenerate honey_bot

Revision ID: 060deeef522c
Revises: 7e3bc4973d6d
Create Date: 2025-09-27 10:35:23.516101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '060deeef522c'
down_revision: Union[str, Sequence[str], None] = '7e3bc4973d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tg_file_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('product_size_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_size_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['public.packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_size_id'], ['public.product_sizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('productsize_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_size_id', sa.Integer(), nullable=False),
    sa.Column('tg_file_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_size_id'], ['public.product_sizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('order_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['public.orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['public.packages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.alter_column('delivery_zones', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('order_delivery', 'delivery_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_delivery', 'delivery_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('order_delivery_delivery_status_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_delivery_zone_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_order_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_delivery_interval_id_fkey'), 'order_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'order_delivery', 'delivery_intervals', ['delivery_interval_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_delivery', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_delivery', 'delivery_zones', ['delivery_zone_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'order_delivery', 'delivery_statuses', ['delivery_status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.add_column('orders', sa.Column('product_count', sa.Integer(), nullable=False))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('orders_session_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_manager_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_status_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_product_size_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_tg_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'product_sizes', ['product_size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'users', ['manager_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('orders', 'drink_count')
    op.alter_column('product_sizes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_sizes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('product_sizes_size_id_fkey'), 'product_sizes', type_='foreignkey')
    op.drop_constraint(op.f('product_sizes_product_id_fkey'), 'product_sizes', type_='foreignkey')
    op.create_foreign_key(None, 'product_sizes', 'sizes', ['size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_sizes', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('products', sa.Column('quantity', sa.Numeric(precision=5, scale=1), nullable=True))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('products_created_by_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_type_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'product_types', ['type_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.add_column('sessions', sa.Column('sent_message', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('sessions_role_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_tg_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('source_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'users', 'sources', ['source_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'source_id')
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_tg_user_id_fkey'), 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sessions_role_id_fkey'), 'sessions', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_column('sessions', 'sent_message')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('products_type_id_fkey'), 'products', 'product_types', ['type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('products_created_by_fkey'), 'products', 'users', ['created_by'], ['tg_user_id'], ondelete='CASCADE')
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('products', 'quantity')
    op.drop_constraint(None, 'product_sizes', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_sizes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('product_sizes_product_id_fkey'), 'product_sizes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_sizes_size_id_fkey'), 'product_sizes', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_sizes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_sizes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('orders', sa.Column('drink_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_tg_user_id_fkey'), 'orders', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_product_size_id_fkey'), 'orders', 'product_sizes', ['product_size_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_status_id_fkey'), 'orders', 'order_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_manager_id_fkey'), 'orders', 'users', ['manager_id'], ['tg_user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('orders_session_id_fkey'), 'orders', 'sessions', ['session_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('orders', 'product_count')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('order_delivery_delivery_interval_id_fkey'), 'order_delivery', 'delivery_intervals', ['delivery_interval_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_delivery_order_id_fkey'), 'order_delivery', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_delivery_delivery_zone_id_fkey'), 'order_delivery', 'delivery_zones', ['delivery_zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('order_delivery_delivery_status_id_fkey'), 'order_delivery', 'delivery_statuses', ['delivery_status_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('order_delivery', 'delivery_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_delivery', 'delivery_cost',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('delivery_zones', 'cost',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_table('order_packages', schema='public')
    op.drop_table('productsize_images', schema='public')
    op.drop_table('product_size_packages', schema='public')
    op.drop_table('images', schema='public')
    op.drop_table('packages', schema='public')
    # ### end Alembic commands ###