"""products.updated_by to fix 2.0

Revision ID: 4e9c21fa028e
Revises: 6171322e8a58
Create Date: 2025-10-09 15:50:42.170112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c21fa028e'
down_revision: Union[str, Sequence[str], None] = '6171322e8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_product_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('order_delivery_delivery_zone_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_order_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_delivery_status_id_fkey'), 'order_delivery', type_='foreignkey')
    op.drop_constraint(op.f('order_delivery_delivery_interval_id_fkey'), 'order_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'order_delivery', 'delivery_statuses', ['delivery_status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_delivery', 'delivery_intervals', ['delivery_interval_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_delivery', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_delivery', 'delivery_zones', ['delivery_zone_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('order_packages_order_id_fkey'), 'order_packages', type_='foreignkey')
    op.drop_constraint(op.f('order_packages_package_id_fkey'), 'order_packages', type_='foreignkey')
    op.create_foreign_key(None, 'order_packages', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_packages', 'packages', ['package_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.drop_constraint(op.f('orders_manager_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_session_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_tg_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_status_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_product_size_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'product_sizes', ['product_size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'users', ['manager_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('product_sizes_size_id_fkey'), 'product_sizes', type_='foreignkey')
    op.drop_constraint(op.f('product_sizes_product_id_fkey'), 'product_sizes', type_='foreignkey')
    op.create_foreign_key(None, 'product_sizes', 'sizes', ['size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_sizes', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('products_updated_by_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_type_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_created_by_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'product_types', ['type_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.drop_constraint(op.f('productsize_images_product_size_id_fkey'), 'productsize_images', type_='foreignkey')
    op.create_foreign_key(None, 'productsize_images', 'product_sizes', ['product_size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_role_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_tg_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sizes_package_id_fkey'), 'sizes', type_='foreignkey')
    op.create_foreign_key(None, 'sizes', 'packages', ['package_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('users_source_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'sources', ['source_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_source_id_fkey'), 'users', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'sizes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sizes_package_id_fkey'), 'sizes', 'packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_tg_user_id_fkey'), 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sessions_role_id_fkey'), 'sessions', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_constraint(None, 'productsize_images', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('productsize_images_product_size_id_fkey'), 'productsize_images', 'product_sizes', ['product_size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('products_created_by_fkey'), 'products', 'users', ['created_by'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('products_type_id_fkey'), 'products', 'product_types', ['type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('products_updated_by_fkey'), 'products', 'users', ['updated_by'], ['tg_user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_sizes', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_sizes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('product_sizes_product_id_fkey'), 'product_sizes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_sizes_size_id_fkey'), 'product_sizes', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_product_size_id_fkey'), 'orders', 'product_sizes', ['product_size_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_status_id_fkey'), 'orders', 'order_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_tg_user_id_fkey'), 'orders', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_session_id_fkey'), 'orders', 'sessions', ['session_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('orders_manager_id_fkey'), 'orders', 'users', ['manager_id'], ['tg_user_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'order_packages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_packages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('order_packages_package_id_fkey'), 'order_packages', 'packages', ['package_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_packages_order_id_fkey'), 'order_packages', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_delivery', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('order_delivery_delivery_interval_id_fkey'), 'order_delivery', 'delivery_intervals', ['delivery_interval_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_delivery_delivery_status_id_fkey'), 'order_delivery', 'delivery_statuses', ['delivery_status_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_delivery_order_id_fkey'), 'order_delivery', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_delivery_delivery_zone_id_fkey'), 'order_delivery', 'delivery_zones', ['delivery_zone_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'images', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('images_product_id_fkey'), 'images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###